name: mikunchik
description: "Plataforma Colaborativa de GastronomÃ­a Local con Enfoque en Sostenibilidad y Accesibilidad Alimentaria."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3
  image_picker: ^1.2.0
  google_sign_in: ^6.1.5
  http: ^1.1.0
  path_provider: ^2.1.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/images/logo.png
    - lib/assets/images/google_icon.png